### ISSUE TITLE
circleci reports the image used here as deprecated

### ISSUE THREAD

**Issue by vandr0iy** [CircleCI-Public/circleci-cli-orb#16]
### Orb version
0.1.9

### What happened

Using a configuration that looks like the following:
```
orbs:
  cli: circleci/circleci-cli@0.1.9

jobs:
  validate_orbs:
    executor: cli/default
    steps:
      - checkout
...

```
I get this error message in the circleci's own app:
![image](https://user-images.githubusercontent.com/5510334/157432137-c0d3fc8b-93da-4f3f-b29f-7c64cd137e22.png)

### Expected behavior

No deprecation messages, obviously :) Please, consider upgrading to cimg/base or adding a new base image with `circleci-cli` installed
